//! Conformance gate against the maximized tier-A vector corpus (26 vectors).
//!
//! For every vector this asserts: (1) the recomputed JCS preimage matches the
//! stored bytes; (2) `verify` returns `Ok(true)`; (3) a deterministic re-sign
//! reproduces the stored HMAC and Ed25519 signatures byte-for-byte; (4) a
//! tampered payload yields `Ok(false)` (not an error); (5) schema detection
//! reports V4. A synthetic legacy record asserts `Err(UnsupportedSchemaV3)`.
//!
//! The corpus is generated by `scripts/gen_vectors.py` against the Python
//! `core/seal` reference; the static list below must mirror its output (the
//! `include_str!` macro needs compile-time paths, so it cannot glob). The
//! `vectors_count_matches_index` test guards against drift between this list
//! and `INDEX.json`.

use apohara_sealchain_core::layers::ed25519 as ed_layer;
use apohara_sealchain_core::schema::SchemaVersion;
use apohara_sealchain_core::{
    build_preimage, detect_schema, seal_deterministic, verify, SealError,
};
use serde_json::Value;

const KEYS: &str = include_str!("vectors/keys.json");

const VECTORS: &[(&str, &str)] = &[
    (
        "vec_01_hmac_only",
        include_str!("vectors/vec_01_hmac_only.json"),
    ),
    (
        "vec_02_hmac_ed",
        include_str!("vectors/vec_02_hmac_ed.json"),
    ),
    (
        "vec_03_simple_v1",
        include_str!("vectors/vec_03_simple_v1.json"),
    ),
    (
        "vec_04_excluded_key",
        include_str!("vectors/vec_04_excluded_key.json"),
    ),
    (
        "vec_05_astral_unicode",
        include_str!("vectors/vec_05_astral_unicode.json"),
    ),
    (
        "vec_06_numbers",
        include_str!("vectors/vec_06_numbers.json"),
    ),
    ("vec_07_nested", include_str!("vectors/vec_07_nested.json")),
    (
        "vec_08_artifact_descriptor",
        include_str!("vectors/vec_08_artifact_descriptor.json"),
    ),
    (
        "vec_09_empty_object",
        include_str!("vectors/vec_09_empty_object.json"),
    ),
    (
        "vec_10_empty_string_values",
        include_str!("vectors/vec_10_empty_string_values.json"),
    ),
    (
        "vec_11_deeply_nested",
        include_str!("vectors/vec_11_deeply_nested.json"),
    ),
    (
        "vec_12_array_mixed",
        include_str!("vectors/vec_12_array_mixed.json"),
    ),
    (
        "vec_13_array_of_objects",
        include_str!("vectors/vec_13_array_of_objects.json"),
    ),
    (
        "vec_14_int_bounds",
        include_str!("vectors/vec_14_int_bounds.json"),
    ),
    (
        "vec_15_floats_edge",
        include_str!("vectors/vec_15_floats_edge.json"),
    ),
    (
        "vec_16_unicode_combining_rtl",
        include_str!("vectors/vec_16_unicode_combining_rtl.json"),
    ),
    (
        "vec_17_jcs_sort",
        include_str!("vectors/vec_17_jcs_sort.json"),
    ),
    (
        "vec_18_all_excluded",
        include_str!("vectors/vec_18_all_excluded.json"),
    ),
    (
        "vec_19_bool_null",
        include_str!("vectors/vec_19_bool_null.json"),
    ),
    (
        "vec_20_repeated_nested_keys",
        include_str!("vectors/vec_20_repeated_nested_keys.json"),
    ),
    (
        "vec_21_large_payload",
        include_str!("vectors/vec_21_large_payload.json"),
    ),
    (
        "vec_22_hmac_only_nested",
        include_str!("vectors/vec_22_hmac_only_nested.json"),
    ),
    (
        "vec_23_hmac_only_unicode",
        include_str!("vectors/vec_23_hmac_only_unicode.json"),
    ),
    (
        "vec_24_artifact_full",
        include_str!("vectors/vec_24_artifact_full.json"),
    ),
    (
        "vec_25_escapes",
        include_str!("vectors/vec_25_escapes.json"),
    ),
    (
        "vec_26_empty_containers",
        include_str!("vectors/vec_26_empty_containers.json"),
    ),
];

/// INDEX.json (generated alongside the vectors) — used to guard the static
/// VECTORS list above against silent drift from `gen_vectors.py`.
const INDEX: &str = include_str!("vectors/INDEX.json");

struct Keys {
    hmac_key: Vec<u8>,
    private_pem: String,
    public_pem: String,
    sealed_at: String,
}

fn load_keys() -> Keys {
    let v: Value = serde_json::from_str(KEYS).expect("keys.json parses");
    let hmac_hex = v["hmac_key_hex"].as_str().expect("hmac_key_hex");
    Keys {
        hmac_key: hex::decode(hmac_hex).expect("hmac key hex decodes"),
        private_pem: v["ed25519_private_pem"]
            .as_str()
            .expect("private pem")
            .to_string(),
        public_pem: v["ed25519_public_pem"]
            .as_str()
            .expect("public pem")
            .to_string(),
        sealed_at: v["sealed_at"].as_str().expect("sealed_at").to_string(),
    }
}

fn strip0x(s: &str) -> &str {
    s.strip_prefix("0x").unwrap_or(s)
}

#[test]
fn conformance_all_vectors() {
    let keys = load_keys();
    let signing_key =
        ed_layer::signing_key_from_pem(&keys.private_pem).expect("private key parses");

    for (name, raw) in VECTORS {
        let record: Value =
            serde_json::from_str(raw).unwrap_or_else(|e| panic!("{name}: parse: {e}"));
        let payload = &record["payload"];
        let seal = &record["seal"];

        // 1. Recomputed preimage equals stored preimage bytes.
        let stored_pre_hex = seal["preimage"].as_str().expect("preimage str");
        let stored_pre = hex::decode(strip0x(stored_pre_hex)).expect("preimage hex");
        let computed_pre = build_preimage(payload, &keys.sealed_at)
            .unwrap_or_else(|e| panic!("{name}: build_preimage: {e}"));
        assert_eq!(
            computed_pre,
            stored_pre,
            "{name}: preimage mismatch\n computed={}\n stored  ={}",
            String::from_utf8_lossy(&computed_pre),
            String::from_utf8_lossy(&stored_pre)
        );

        // 2. verify returns Ok(true). hmac-only vectors pass None for pubkey.
        let has_ed = seal.get("ed25519").is_some();
        let pubkey = if has_ed {
            Some(keys.public_pem.as_str())
        } else {
            None
        };
        let ok = verify(&record, &keys.hmac_key, pubkey)
            .unwrap_or_else(|e| panic!("{name}: verify errored: {e}"));
        assert!(ok, "{name}: verify returned Ok(false) for a valid record");

        // 3. Deterministic re-sign reproduces stored signatures byte-for-byte.
        let ed_opt = if has_ed { Some(&signing_key) } else { None };
        let resigned = seal_deterministic(payload, &keys.hmac_key, ed_opt, &keys.sealed_at)
            .unwrap_or_else(|e| panic!("{name}: seal_deterministic: {e}"));

        let stored_hmac = seal["hmac"]["sig"].as_str().expect("hmac sig");
        assert_eq!(
            resigned.seal.hmac.sig, stored_hmac,
            "{name}: hmac sig mismatch"
        );

        if has_ed {
            let stored_ed = seal["ed25519"]["sig"].as_str().expect("ed sig");
            let produced_ed = resigned
                .seal
                .ed25519
                .as_ref()
                .expect("ed25519 produced")
                .sig
                .as_str();
            assert_eq!(produced_ed, stored_ed, "{name}: ed25519 sig mismatch");
        } else {
            assert!(
                resigned.seal.ed25519.is_none(),
                "{name}: unexpected ed25519 layer produced"
            );
        }

        // 4. Tamper: mutate a payload value, verify must return Ok(false).
        let mut tampered = record.clone();
        tamper_payload(&mut tampered["payload"]);
        let tamper_res = verify(&tampered, &keys.hmac_key, pubkey)
            .unwrap_or_else(|e| panic!("{name}: tamper verify errored: {e}"));
        assert!(
            !tamper_res,
            "{name}: tampered record verified as valid (expected Ok(false))"
        );

        // 5. Schema detection reports V4.
        let sv = detect_schema(&record).unwrap_or_else(|e| panic!("{name}: detect_schema: {e}"));
        assert_eq!(sv, SchemaVersion::V4, "{name}: expected V4");
    }
}

/// Keys stripped before sealing — mutating these must NOT change the seal, so
/// the tamper test deliberately avoids them to produce a real preimage change.
const EXCLUDED: [&str; 6] = [
    "kg_status",
    "kg_latency_ms",
    "surface_status",
    "truncated",
    "charsSeen",
    "lowConfidenceTier",
];

/// Mutate the first non-excluded scalar in the payload so the preimage changes.
fn tamper_payload(payload: &mut Value) {
    match payload {
        Value::Object(map) => {
            for (k, v) in map.iter_mut() {
                if EXCLUDED.contains(&k.as_str()) {
                    continue;
                }
                if tamper_scalar(v) {
                    return;
                }
            }
            // No non-excluded scalar at the top level — force a new key.
            map.insert("__tamper__".to_string(), Value::Bool(true));
        }
        other => {
            tamper_scalar(other);
        }
    }
}

/// If `v` is a scalar, mutate it in place and return true.
fn tamper_scalar(v: &mut Value) -> bool {
    match v {
        Value::String(s) => {
            s.push_str("-tampered");
            true
        }
        Value::Bool(b) => {
            *b = !*b;
            true
        }
        Value::Number(_) => {
            *v = Value::String("tampered".to_string());
            true
        }
        Value::Null => {
            *v = Value::Bool(true);
            true
        }
        Value::Object(_) | Value::Array(_) => false,
    }
}

#[test]
fn detect_schema_rejects_legacy_v3() {
    // Top-level sealedAt, no seal.sealedAt -> legacy v3.
    let v3: Value = serde_json::json!({
        "sealedAt": "2026-01-01T00:00:00+00:00",
        "payload": { "verdict": "ok" },
        "seal": { "method": "apohara-seal-v1" }
    });
    let err = detect_schema(&v3).expect_err("v3 must be rejected");
    assert!(
        matches!(err, SealError::UnsupportedSchemaV3),
        "expected UnsupportedSchemaV3, got {err:?}"
    );
}

/// Guard against drift: the static VECTORS list must cover the full generated
/// corpus. If `gen_vectors.py` adds a vector but the list above is not updated,
/// this fails (the new vector would otherwise be silently un-tested).
#[test]
fn vectors_count_matches_index() {
    let index: Value = serde_json::from_str(INDEX).expect("INDEX.json parses");
    let count = index["count"].as_u64().expect("INDEX count") as usize;
    assert_eq!(
        VECTORS.len(),
        count,
        "VECTORS list ({}) is out of sync with INDEX.json ({}); update conformance.rs after re-running gen_vectors.py",
        VECTORS.len(),
        count
    );
}
